language: ruby
rvm:
- 2.4.1
deploy:
  provider: heroku
  api_key:
    secure: fA/JR7h9rbsx+CiqwkQkLADKFVrzIq3a5VLPDP/5207Q70SHtWdFJOq/fKInFtab8pFWER0FqfI/rRH8WuDwZ0yUOzT0hU7hc9+dyrVbPJTh1qLZfTZ/FkIg9VAa2lafq+ZBOiiXCQubtb0y28oWVw/sthsC4M6L6gi1cgAm+Q8lUiVREWGUVlcZ3ukTS6Xc5EJkhlmeaXhoP7TkMxoc28RJkip/EHvkhzPlsVIbZoa/kDX57wglN9nvCYtxVXuW4heK5McxeEHhrei1lxox5++nkZJ2UxjOIuQ+1vuWPQzerDWsEe3PEa1MyBZTfukr0HgejzY3aYDJPk0q8sEtD0OgmDNiLpkWj/kxP2pF46R2CiHi4kv4B0aIf7NznZsWeHbJQGwTAKXKgVT8brzvBqxpV5sFStUi19iVSXQsDB6cQAigR9WPxAgNgi3n+OSOKwHDMzx7wj6DYamaGezIllEZ8fiAb1/9/RELWcVUAYUIUDBgqAq0TW6L7ohA8lKmEEppU07XQBmyTz0AECZ0E9YD14y1zgwuKRDgBLCBgP8yzG0guqpEqZXE/06l3pH1GuTMxKca0uB4UcF+aY9LVIBI05xe/pOaesRxWSLOS/2hhsH0d7by69QdbhFQ6kaGqLQvsdu/p3cx1hQi2L1OtPPJC2g5GLpFDfOqAhtU8r8=
  app: high-five5
  on:
    repo: himajin315/high-five
script: bundle exec rspec spec
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
before_script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8
