language: ruby
rvm:
- 2.4.1
deploy:
  provider: heroku
  api_key:
    - secure: cHbHOYZw4p1LbIqfj/6EFu9oyzAJAzdREdP3M/okJD5LZgB8A0R4KnwTxWxWCoRNGPaYhTU6xUzXATUyBLSN33uyWI9r226oCjceMi6IlB/tZNFCvAo8WTVYGu3mXf+x50kqwR2O17t4BcHWeg2hrPnZJGx/Y04rrFQMI7mE4t4t5cJ5vO7XOW7vWplVOPM/9bvWSNm6jT41VTDVVrslLvIpQwMEYPmGF6Zp/GGdBAor1Vo5TQD2M+1ufnRVms0MQYvJEP0scPXzubYFErBsZjkA8hmWlFZlLUz7hUTpLFcmtlO0h5CSDZGH9dltKMK/4oZfxKThEd4im+VqoS/L1SZO0nuKlTlvW0LmASV21TmHoFwwv9bqj6WaU+v5Of42tpizHa4S0MyOTJNPX5HYGnuo4IAevNl2kKBtUIQDWsWi8ZYPuJkQXiyUqB/GZ2Qt/TfP0R6WuGqRQzizOivP1PaUELUZ6InxchTszgKr7hYXWjvCMTepI1PaxGp2ihku4QnAQyqaSQFx5fbpFQfMJGQ/Gr3qNhwdfF14tcOY3ItLj4poJgBpA2MwB2kPGTSnmYjy3qt68tz9caOEV3UDWT3u7+93ZTc51aemaUIpVC9H8jXw1/Fij9KfeB/B5OxzflFA+hjBXixrXDyt0INpef5JTGwxKwJVeCFFaZNtc9Y=
  app: high-five5
  on:
    repo: himajin315/high-five
script: bundle exec rspec spec
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
before_script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8
